### ISSUE TITLE
redis 4.0.12 and 4.0.13

### ISSUE THREAD

**Issue by petterthunaes** [iuscommunity-pkg/redis40u#2]
Hi,

Just wanted to ask if it is possible to get version 4.0.12 and 4.0.13 added to the IUS repo?

Thanks,

Petter

**Comment by carlwgeorge** [comment]
I don't see the point in doing 4.0.12 now, I'd rather just get it updated to the latest upstream version.  I've done that in 8993ebfee660e52ce739893d558a0cd9570db1eb.  [redis40u-4.0.13-1](https://github.com/iuscommunity-pkg/redis40u/releases/tag/4.0.13-1) has been built and will move to the testing repos during tonight's automation.
